name: projeto-mobile

services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: backend.dockerfile
    
  frontend:
    image: frontend
    build: 
      context: frontend
      dockerfile: frontend.dockerfile
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore: 
            - node_modules/